### ISSUE TITLE
Actualizar button en pagina "vivienda.php"

### ISSUE THREAD

**Issue by angelgt28** [Agencia-Servitec/cobiene#13]
- Actualizar button "Requisitos para ser un usuarios"

![image](https://user-images.githubusercontent.com/104872504/169922041-a91d3aad-3c8f-442c-9630-124fb26b735f.png)

**Comment by adminAgenciaServitec** [comment]
@EduardXI La solución es simple:

Es solo corregir el nombre de id y agregar la clase:

![Screen Shot 2022-05-24 at 10 57 59 AM](https://user-images.githubusercontent.com/104750139/170080244-4810b29f-2625-4671-8d9a-32ab74082939.png)
